branches:
  only:
    - master
    - staging
    - production
  services:
    #Enable docker service inside travis
    - docker
  script:
    #build the image
    - bash config/buildDockerImage.sh
  env:
    - $DOCKER_IMAGE_NAME="3blades/traefik"
